name: Validate

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions: {}

jobs:
  validate-hacs:
    runs-on: ubuntu-24.04
    steps:
      - name: HACS validation
        uses: hacs/action@main
        with:
          category: integration

  hassfest:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Hassfest
        uses: home-assistant/actions/hassfest@master
